In [19]:
import numpy as np
import matplotlib.pyplot as plt
import cv2

from sklearn.datasets import load_diabetes
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix   
from sklearn.linear_model import LogisticRegression

# Diabetes dataset for regression or classification: 
# The goal of the script is to first classify if a patient 
# has diabetes or not based on multiple features like:
#   Patient age
#   Patient sex
#   Patient BMI
#   Patient average blood pressure
#   Six blood serum measurements
# All of these features are measured on 442 patients, and used
# as an indicator of disease progression after one year.

# First we load the dataset
# Here we see that the "x" value represents each person and their
# 10 features. While the "y" values represents each person.
# The diabetes dataset is returned as a "regression" dataset
data = load_diabetes()
x, y = data['data'], data['target']
print(data["feature_names"])
print(x.shape)
print(y.shape)
print(x[0][0])

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']
(442, 10)
(442,)
0.0380759064334241


In [2]:
# Since the diabetes dataset is loaded as a regression dataset,
# we have to convert it to a classification problem.

# First we create an array of zeros with the same size as "y"
# Then we set each element to 1 in our "y_" array, where in the "y" array
# the correspoding element is bigger than 140. Then we convert the values
# of decimals in "y_" to integers.
y_ = np.zeros(y.shape)
y_[y > 140] = 1.
y_ = y_.astype(int)

In [3]:
# Then we split our data into 80% training data and 20% testing data
# The "random_state" parameter is used for reprodruction of the data. 
# The stratify parameter makes sure that "y_" is equally represented 
# in both training and test. This type of setup is called holdout.
x_train, x_test, y_train, y_test = train_test_split(x, y_, test_size=0.2, random_state=42, stratify=y_)
print("Train dataset:", x_train.shape, y_train.shape)
print("Test dataset", x_test.shape, y_test.shape)

Train dataset: (353, 10) (353,)
Test dataset (89, 10) (89,)


In [20]:
# Standardise the data so that all the data has a range between 0 and 1, 
# instead of between -1 and 1.
min_max_scaler = MinMaxScaler(feature_range=(0,1))
x_train_ = min_max_scaler.fit_transform(x_train)
x_test_ = min_max_scaler.fit_transform(x_test)

[[0.66666667 1.         0.42180095 ... 0.42313117 0.54263407 0.72727273]
 [0.56666667 0.         0.28909953 ... 0.28208745 0.54549947 0.56060606]
 [0.05       0.         0.23696682 ... 0.14104372 0.20026662 0.5       ]
 ...
 [0.71666667 1.         0.65402844 ... 0.42313117 0.5702869  0.60606061]
 [0.25       1.         0.12322275 ... 0.         0.15120886 0.51515152]
 [0.23333333 1.         0.3507109  ... 0.42313117 0.56492788 0.71212121]]
